// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  userId: __t.u64().name("user_id"),
  deviceId: __t.string().name("device_id"),
  changeType: __t.string().name("change_type"),
  actorUserId: __t.u64().name("actor_user_id"),
  actorDeviceId: __t.option(__t.string()).name("actor_device_id"),
};
