// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  conversationId: __t.string().name("conversation_id"),
  kind: __t.string(),
  title: __t.string(),
  createdByUserId: __t.u64().name("created_by_user_id"),
  createdAt: __t.timestamp().name("created_at"),
  lastMessageAt: __t.timestamp().name("last_message_at"),
  lastMessageId: __t.option(__t.string()).name("last_message_id"),
  participantUserIds: __t.array(__t.u64()).name("participant_user_ids"),
});
