// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  eventId: __t.string().name("event_id"),
  conversationId: __t.string().name("conversation_id"),
  eventType: __t.string().name("event_type"),
  targetUserId: __t.u64().name("target_user_id"),
  targetDeviceId: __t.option(__t.string()).name("target_device_id"),
  actorUserId: __t.u64().name("actor_user_id"),
  actorDeviceId: __t.option(__t.string()).name("actor_device_id"),
  newEpoch: __t.u32().name("new_epoch"),
  createdAt: __t.timestamp().name("created_at"),
});
