// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  packageId: __t.string().name("package_id"),
  conversationId: __t.string().name("conversation_id"),
  epoch: __t.u32(),
  recipientUserId: __t.u64().name("recipient_user_id"),
  recipientDeviceId: __t.string().name("recipient_device_id"),
  senderUserId: __t.u64().name("sender_user_id"),
  senderDeviceId: __t.string().name("sender_device_id"),
  sealedSenderKey: __t.string().name("sealed_sender_key"),
  createdAt: __t.timestamp().name("created_at"),
});
