// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  payloadId: __t.string().name("payload_id"),
  messageId: __t.string().name("message_id"),
  conversationId: __t.string().name("conversation_id"),
  senderUserId: __t.u64().name("sender_user_id"),
  senderDeviceId: __t.string().name("sender_device_id"),
  protocolVersion: __t.string().name("protocol_version"),
  messageType: __t.string().name("message_type"),
  conversationEpoch: __t.u32().name("conversation_epoch"),
  deliveryScope: __t.string().name("delivery_scope"),
  recipientUserId: __t.option(__t.u64()).name("recipient_user_id"),
  recipientDeviceId: __t.option(__t.string()).name("recipient_device_id"),
  ciphertext: __t.string(),
  nonce: __t.string(),
  aad: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
