// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  typingStateId: __t.string().name("typing_state_id"),
  conversationId: __t.string().name("conversation_id"),
  userId: __t.u64().name("user_id"),
  isTyping: __t.bool().name("is_typing"),
  updatedAt: __t.timestamp().name("updated_at"),
});
