// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  conversationId: __t.string(),
  protocolVersion: __t.option(__t.string()).name("protocol_version"),
  messageType: __t.option(__t.string()).name("message_type"),
  conversationEpoch: __t.option(__t.u32()).name("conversation_epoch"),
  ciphertext: __t.option(__t.string()),
  payloads: __t.option(__t.array(__t.row({
    deliveryScope: __t.string().name("delivery_scope"),
    recipientUserId: __t.option(__t.u64()).name("recipient_user_id"),
    recipientDeviceId: __t.option(__t.string()).name("recipient_device_id"),
    ciphertext: __t.string(),
    nonce: __t.string(),
    aad: __t.string(),
  }))),
};
