// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AdminIdentity = __t.object("AdminIdentity", {
  identity: __t.identity(),
  createdAt: __t.timestamp(),
});
export type AdminIdentity = __Infer<typeof AdminIdentity>;

export const AppUserIdentity = __t.object("AppUserIdentity", {
  userId: __t.u64(),
  identity: __t.identity(),
  createdAt: __t.timestamp(),
});
export type AppUserIdentity = __Infer<typeof AppUserIdentity>;

export const Conversation = __t.object("Conversation", {
  conversationId: __t.string(),
  kind: __t.string(),
  title: __t.string(),
  createdByUserId: __t.u64(),
  createdAt: __t.timestamp(),
  lastMessageAt: __t.timestamp(),
  lastMessageId: __t.option(__t.string()),
});
export type Conversation = __Infer<typeof Conversation>;

export const ConversationMember = __t.object("ConversationMember", {
  memberId: __t.string(),
  conversationId: __t.string(),
  userId: __t.u64(),
  identity: __t.identity(),
  joinedAt: __t.timestamp(),
});
export type ConversationMember = __Infer<typeof ConversationMember>;

export const ConversationViewRow = __t.object("ConversationViewRow", {
  conversationId: __t.string(),
  kind: __t.string(),
  title: __t.string(),
  createdByUserId: __t.u64(),
  createdAt: __t.timestamp(),
  lastMessageAt: __t.timestamp(),
  lastMessageId: __t.option(__t.string()),
  participantUserIds: __t.array(__t.u64()),
});
export type ConversationViewRow = __Infer<typeof ConversationViewRow>;

export const DmPair = __t.object("DmPair", {
  pairKey: __t.string(),
  conversationId: __t.string(),
  createdAt: __t.timestamp(),
});
export type DmPair = __Infer<typeof DmPair>;

export const Message = __t.object("Message", {
  messageId: __t.string(),
  conversationId: __t.string(),
  senderUserId: __t.u64(),
  senderIdentity: __t.identity(),
  ciphertext: __t.string(),
  createdAt: __t.timestamp(),
});
export type Message = __Infer<typeof Message>;

export const MyConversations = __t.object("MyConversations", {});
export type MyConversations = __Infer<typeof MyConversations>;

export const MyMessages = __t.object("MyMessages", {});
export type MyMessages = __Infer<typeof MyMessages>;

export const MyPresence = __t.object("MyPresence", {});
export type MyPresence = __Infer<typeof MyPresence>;

export const MyReadState = __t.object("MyReadState", {});
export type MyReadState = __Infer<typeof MyReadState>;

export const MyTyping = __t.object("MyTyping", {});
export type MyTyping = __Infer<typeof MyTyping>;

export const Presence = __t.object("Presence", {
  userId: __t.u64(),
  identity: __t.identity(),
  activeConnections: __t.u32(),
  isOnline: __t.bool(),
  lastSeenAt: __t.timestamp(),
});
export type Presence = __Infer<typeof Presence>;

export const PresenceViewRow = __t.object("PresenceViewRow", {
  userId: __t.u64(),
  identity: __t.identity(),
  activeConnections: __t.u32(),
  isOnline: __t.bool(),
  lastSeenAt: __t.timestamp(),
});
export type PresenceViewRow = __Infer<typeof PresenceViewRow>;

export const ReadCursor = __t.object("ReadCursor", {
  readCursorId: __t.string(),
  conversationId: __t.string(),
  userId: __t.u64(),
  lastReadMessageId: __t.string(),
  lastReadAt: __t.timestamp(),
});
export type ReadCursor = __Infer<typeof ReadCursor>;

export const TypingState = __t.object("TypingState", {
  typingStateId: __t.string(),
  conversationId: __t.string(),
  userId: __t.u64(),
  isTyping: __t.bool(),
  updatedAt: __t.timestamp(),
});
export type TypingState = __Infer<typeof TypingState>;

